language: cpp
compiler:
    - gcc
before_install:
    # disable rvm, use system Ruby
    - rvm reset
    - wget https://raw.githubusercontent.com/yast/yast-devtools/master/travis-tools/travis_setup.sh
    - sh ./travis_setup.sh -p "rake yast2-devtools" -g "yast-rake yard rspec:3.3.0 gettext"
script:
    - rake check:syntax
    - rake check:pot
    - yardoc
    - rake test:unit
    - sudo rake install

